title: Data Patterns
author: Open Knowledge Labs
authorurl: http://okfnlabs.org/
# baseurl: /my-subsite
# optional links (will go in navbar and footer)
github: http://github.com/okfn/datapatterns
mailinglist: http://lists.okfn.org/mailman/listinfo/okfn-labs
twitter: OKFNLabs
openknowledgeribbon: true
# googleanalytics:
defaults:
  -
    scope:
      path: "text"
    values:
      layout: "default"
