title: Data Patterns
short_title: Labs Handbook
description: "A collection of guides and advice to participate in Open Knowledge Labs"
baseurl: ""
issues_url: http://github.com/okfn/datapatterns/issues
url: "http://datapatterns.org/"
github_username: okfn
github_repo: datapatterns
paypal: admin@okfn.org
contact: "https://discuss.okfn.org/c/open-knowledge-labs"
markdown: redcarpet
highlighter: pygments
gems:
  - jekyll-redirect-from
  - jekyll-mentions
devs:
  -
      name: Sam Smith
      github: mintcanary
  -
      name: Dan Fowler
      github: danfowler

      name: Gustavo Silva
      github: gsilvapt

permalink: pretty
openknowledgeribbon: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      edit: true
